- name: install pip
  shell:
    curl -kL https://raw.github.com/pypa/pip/master/contrib/get-pip.py | python2.7
  environment:
    PATH: "{{ python_dir }}/bin:{{ ansible_env.PATH }}"
  tags:
    - pip

- name: install pypi
  pip:
    name="{{ item }}" state=present
  with_items:
    - "https://pypi.python.org/packages/source/D/Django/Django-1.7.1.tar.gz#md5=81dae89f21647b9aa5c46c6b7dbfa349"
    - "https://pypi.python.org/packages/source/M/MySQL-python/MySQL-python-1.2.5.zip#md5=654f75b302db6ed8dc5a898c625e030c"
    - "https://pypi.python.org/packages/source/x/xlrd/xlrd-0.9.3.tar.gz#md5=6f3325132f246594988171bc72e1a385"
    - "https://pypi.python.org/packages/source/x/xlutils/xlutils-1.7.1.tar.gz"
    - "https://pypi.python.org/packages/source/M/MarkupSafe/MarkupSafe-0.23.tar.gz"
    - "https://pypi.python.org/packages/source/J/Jinja2/Jinja2-2.7.3.tar.gz"
    - "https://pypi.python.org/packages/source/v/virtualenv/virtualenv-1.11.6.tar.gz#md5=f61cdd983d2c4e6aeabb70b1060d6f49"
    - "https://pypi.python.org/packages/source/v/virtualenvwrapper/virtualenvwrapper-4.3.1.tar.gz"
    - "https://pypi.python.org/packages/source/p/passlib/passlib-1.6.2.tar.gz"
    - "https://pypi.python.org/packages/source/P/PyYAML/PyYAML-3.11.tar.gz#md5=f50e08ef0fe55178479d3a618efe21db"
  environment:
    PATH: "{{ python_dir }}/bin:{{ ansible_env.PATH }}"
  tags:
    - pip

