- name: install httpd httpd-tools httpd-devel
  yum: name="{{ item }}" state=present
  with_items:
    - "httpd"
    - "httpd-tools"
    - "httpd-devel"
  tags:
    - httpd

- name: copy httpd.conf
  template:
    src="{{ httpd_config_file_src }}"
    dest="{{ httpd_config_file_dst }}"
    owner="root"
    group="root"
    mode="644"
  tags:
    - httpd

#- name: copy httpd.conf
#  copy:
  #    src="{{ httpd_config_src_file }}"
  #    dest="{{ httpd_config_dst_file }}"
  #    owner="root"
  #    group="root"
  #    mode="644"
  #  tags:
    #    - httpd

- name: start httpd && chekconfig on
  service: name="httpd" state="started" enabled="yes"
  tags:
    - httpd

